
package tests;
import org.testng.annotations.Test;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;
import org.testng.annotations.BeforeMethod;
import static io.restassured.RestAssured.given;
import static org.hamcrest.CoreMatchers.equalTo;
import java.util.HashMap;
import java.util.Map;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.DataProvider;
import org.testng.annotations.Test;
import io.restassured.builder.RequestSpecBuilder;
import io.restassured.builder.ResponseSpecBuilder;
import io.restassured.http.ContentType;
import io.restassured.response.Response;
import io.restassured.specification.RequestSpecification;
import io.restassured.specification.ResponseSpecification;

import org.testng.Reporter;

public class TestGithubAPIs {
	
	RequestSpecification requestSpec;
	ResponseSpecification responseSpec;
	String sshKey,sshId;
	
	@BeforeClass
	public void setUp() {
		requestSpec=new RequestSpecBuilder()
				.addHeader("Content-Type", "application/json")
				.setBaseUri("https://api.github.com")
				.addHeader("Authorization", "Bearer token")
				.build();
		/*
		 * responseSpec=new ResponseSpecBuilder() .expectStatusCode(200)
		 * .expectContentType("application/json") .expectBody("status",equalTo("alive"))
		 * .build();
		 */
	}
	
	
	@Test(priority=1)
	public void post() {
		String reqBody = "{\n" +
		        "  \"title\": \"TestAPIKey\",\n" +
		        "  \"key\": \"ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDL/8MQHfSFfpLjWe0AKg7otQtkc68bVVl8qjSy7+U3pvY4HSzGIkL1ZWOgiEw327Z1S/2ic1kEtsXMGr+AWUeb8KZyNpge0S7BSf+c5QZqkdnlwV0N/D/DSx0HR0iHiA89Bu8fMAKK7GxX5VSQAYePOOvvsk1Quz9LIayY2WYQHYexeGN1Pm11NG+Hqt3XZL1fncDOiqxF1eCcfzJDPOsrFdV69MIpSz5lDGyxsWJydQ09pCJbQPHa0DuHwOyiCPwP0KjzK0S4mVJ4UU6SB64QxRXlywH99CmJL4lTkcTjFBfrk0WrcPoVvZVg8HsSSIYnMf5K48FRnChtyHlL/JWR Generated by ShowDNS - 2026-01-14\"\n" +
		        "}";
		sshId=given()
	    .baseUri("https://api.github.com")
	    .contentType(ContentType.JSON)
	    .header("Authorization", "Bearer " + "token")
	    .body(reqBody)
	.when()
	    .post("/user/keys")
	.then()
	    .statusCode(201)
	    .extract().jsonPath().getString("id");
		System.out.println("id "+sshId);
		
	}
	
	@Test(priority=2)
	public void get() {

	    Reporter.log("========== GET /user/keys/{id} ==========", true);
	    Reporter.log("SSH Key ID: " + sshId, true);

	    Response response =
	        given()
	            .spec(requestSpec)
	            .pathParam("keyId", sshId)
	        .when()
	            .get("/user/keys/{keyId}");

	    // Assertions
	    response.then().statusCode(200);

	    // Log response using Reporter.log ONLY
	    Reporter.log("Status Code: " + response.getStatusCode(), true);
	    Reporter.log("Response Headers: " + response.getHeaders().toString(), true);
	    Reporter.log("Response Body:", true);
	    Reporter.log(response.getBody().asPrettyString(), true);

	    Reporter.log("========== GET SUCCESS ==========", true);
	}

	
	@Test(priority=3)
	public void delete() {
		Reporter.log("========== DELETE /user/keys/{id} ==========", true);
	    Reporter.log("SSH Key ID: " + sshId, true);
		Response response=given().spec(requestSpec)
		.pathParam("keyId",sshId)
		.when()
		.delete(" /user/keys/{keyId}");
		response.then().statusCode(204);
		Reporter.log("Status Code: " + response.getStatusCode(), true);
	    Reporter.log("Response Headers: " + response.getHeaders().toString(), true);
	    Reporter.log("Response Body:", true);
	    Reporter.log(response.getBody().asPrettyString(), true);

	    Reporter.log("========== DELETE SUCCESS ==========", true);
		
		
		
	}
	

}
